# Generated by Django 2.2.22 on 2021-05-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('recipient', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('raw_content', models.TextField()),
                ('inbound', models.BooleanField(default=False)),
                ('bounced', models.BooleanField(default=False)),
            ],
        ),
    ]
