# Generated by Django 2.2.23 on 2021-09-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailkeeper', '0002_auto_20210901_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='extended_delivery_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='email',
            name='status',
            field=models.CharField(blank=True, choices=[('sent', 'Sent'), ('bounced', 'Bounced')], max_length=12),
        ),
    ]
