# Generated by Django 2.2.23 on 2021-09-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailkeeper', '0004_correct_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='extended_delivery_status',
            field=models.TextField(blank=True),
        ),
    ]
