all:
  hosts:
      srv1:
        ansible_host: 192.168.122.101
        ansible_port: 22
      srv2:
        ansible_host: 192.168.122.102
        ansible_port: 22

  children:
    all_servers:
      hosts:
        srv1:
        srv2:
