all:
  hosts:
      bratishka:
        ansible_host: 192.168.122.101
        ansible_port: 22
      petro:
        ansible_host: 192.168.122.103
        ansible_port: 22
      master:
        ansible_host: 192.168.122.102
        ansible_port: 22
      srv1:
        ansible_host: 192.168.122.101
        ansible_port: 22
      srv2:
        ansible_host: 192.168.122.102
        ansible_port: 22

  children:
    all_servers:
      hosts:
        bratishka:
        petro:
        master:
        srv1:
        srv2:
      vars:
        main_rabbit: false
        django_app_needed: false
    primary:
      hosts:
        bratishka:
    secondary:
      hosts:
        petro:
    main:
      hosts:
        master:
    main_rabbit_srv:
      hosts:
        srv2:
      vars:
        main_rabbit: true
    django_app:
      hosts:
        srv2:
      vars:
        django_app_needed: true
